### ISSUE TITLE
Installing upp/10.0.3 at the hpc-stack

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#140]
**Is your feature request related to a problem? Please describe.**
A new version UPP is available for building standalone UPP via cmake. Please install upp lib upp/10.0.3 at the hpc-stack on WCOSS, Hera, Jet, and Orion.

**Describe the solution you'd like**
The tag upp_v10.0.3 can be downloaded from the UPP repository.

**Additional context**

**Comment by kgerheiser** [comment]
Do we need to install every point release? Is 10.0.1, 10.0.2 and 10.0.3 necessary? I think hpc-stack should focus on the users of the libraries rather than automatically installing each library release as it comes out (unless someone needs that particular version).

The weather model is using version 10.0.0 and we'll keep that as the default version in the stack files until they update. There is some major release coming relatively soon with inline post that the weather model will want, right? Could we even wait until that version to install a new version of UPP?


We can install any versions necessary, but would also like to keep the installation tree free from version clutter if possible.

**Comment by WenMeng-NOAA** [comment]
@kgerheiser You are right. I realized too many requests for installation. At this time, I would like to install 10.0.1 first due to a bug fix for the current in-line post and also some model developers would like to use the version without the UPP refactor merge (10.0.2) for their experiments. We might skip 10.0.2 and 10.0.3 and install 10.0.4 after regional in-line post will be integrated.

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA and I will install 10.0.1 tomorrow, and then we can figure out any other versions you may also want.

**Comment by WenMeng-NOAA** [comment]
@kgerheiser Great, Thanks!

**Comment by Hang-Lei-NOAA** [comment]
The post new versions have been installed on Hera, WCOSS dell, and cray(under NCEPLIBS v1.3.0)

**Comment by WenMeng-NOAA** [comment]
@Hang-Lei-NOAA Thanks!

**Comment by kgerheiser** [comment]
Yes, it's on all platforms now. Going to close this issue.

**Comment by climbfuji** [comment]
> Yes, it's on all platforms now. Going to close this issue.

Is it on Cheyenne? That is a tier-1 platform for the UFS weather model, too.

**Comment by kgerheiser** [comment]
No, we did Hera, Jet, Orion, and WCOSS. We don't have access to Cheyenne. If you could install it there, please.

**Comment by climbfuji** [comment]
> No, we did Hera, Jet, Orion, and WCOSS. We don't have access to Cheyenne. If you could install it there, please.

I can do that, sure. We also need to do gaea, I suppose. Did you install in the existing 1.1.0 tree?

**Comment by climbfuji** [comment]
Installed on Cheyenne for both Intel and GNU, and on Gaea for Intel.

**Comment by WenMeng-NOAA** [comment]
@climbfuji Thanks for installing on Gaea. We have a UPP user had asked upp lib availability on Gaea. I will let him know it.

**Comment by kgerheiser** [comment]
We are on to 10.0.8.
