### ISSUE TITLE
Question from user about how to use NCEPLIBS on WCOSS machine

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#164]
Question from a user:

```
Partha Bhattacharjee - NOAA Affiliate <partha.bhattacharjee@noaa.gov>
Fri, Feb 12, 6:26 PM (9 hours ago)
to me

Hi Edward,
 I need some help to set up a package in Hera and Raghu suggested your name. So, I am trying to use NCEPLIB modules in Hera to generate executable but, I need help how to set them properly. 
My working directory is 
/scratch1/NCEPDEV/global/Partha.Bhattacharjee/Veri_pkg/PREP/sorc
and getting following error :
sorc]$ make
ifort -recursive -qopenmp -convert big_endian mkclimn.o miscng.o -o ../exec/mkclimn.x -L/scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles -lsp -lip2 -lw3nco -lw3emc -lbacio -lbufr
ld: cannot find -lsp
ld: cannot find -lip2
ld: cannot find -lw3nco
ld: cannot find -lw3emc
ld: cannot find -lbacio
ld: cannot find -lbufr
make: *** [mkclimn.x] Error 1

I can see those required libraries under  /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles , but how to best use them in Makefle I am not sure. Any help  on this is well appreciated
Thanks
Partha

```

**Comment by Hang-Lei-NOAA** [comment]
Hi, Partha,

I noticed that you are using the NCO style NCEPLIBS.
The correct way to use library in the old way is to give the path of
library file, not modulefiles.
For example, if you want to use nemsio library. The modulefile is
on /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles/nemsio/2.2.4 but the
library file is on
/scratch2/NCEPDEV/nwprod/NCEPLIBS/compilers/intel/
19.0.4.243/lib/libnemsio_v2.2.4.a

So, you have to set
-L/scratch2/NCEPDEV/nwprod/NCEPLIBS/compilers/intel/19.0.4.243/lib
-lnemsio_v2.2.4

Or you can do
module load nemsio/2.2.4
-bash-4.2$ module show nemsio/2.2.4
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles/nemsio/2.2.4:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conflict("nemsio")
setenv("NEMSIO_VER","v2.2.4")
setenv("NEMSIO_SRC","/scratch2/NCEPDEV/nwprod/NCEPLIBS/src/nemsio_v2.2.4")
setenv("NEMSIO_INC","/scratch2/NCEPDEV/nwprod/NCEPLIBS/compilers/intel/
19.0.4.243/include/nemsio_v2.2.4")
setenv("NEMSIO_LIB","/scratch2/NCEPDEV/nwprod/NCEPLIBS/compilers/intel/
19.0.4.243/lib/libnemsio_v2.2.4.a")
setenv("LIB_NAME","NEMSIO")
setenv("COMP","intel")
help([[Set environment variables for nemsio library, including NEMSIO_SRC,
NEMSIO_INC, and NEMSIO_LIB
]])

to check the module set up, and use ${NEMSIO_LIB} in your build.

Otherwise, we also have the latest installation of hpc-stack for now and
future use.  This is the EIB recommended way.
Please read the this page to know how to use NCEPLIBS through hpc-stack
installations:
https://github.com/NOAA-EMC/hpc-stack/wiki/Official-Installations

Thanks,
Hang

**Comment by aerorahul** [comment]
This is not an hpc-stack related issue.
