### ISSUE TITLE
Update CMake to 3.20.1

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#220]
Building the weather model with external FMS requires CMake 3.19+ which will be installed with hpc-stack.

**Comment by edwardhartnett** [comment]
When I look at the FMS CMakeLists.txt file, I see:

`cmake_minimum_required(VERSION 3.7...3.15 FATAL_ERROR)
`
So this does not seem to require 3.19+. Which package does?

Probably whatever that package is, does not really need 3.19. Probably that programmer just selected the current version on their system as the minimum version, without considering that this would cause extra work as everyone has to upgrade their CMake version.

We should not let a whimsical decision drive this much effort. If there is a real reason to go to CMake 3.19, we should hear it. Otherwise, we should push back and tell everyone to use a more reasonable version.

**Comment by climbfuji** [comment]
> When I look at the FMS CMakeLists.txt file, I see:
> 
> `cmake_minimum_required(VERSION 3.7...3.15 FATAL_ERROR) `
> So this does not seem to require 3.19+. Which package does?
> 
> Probably whatever that package is, does not really need 3.19. Probably that programmer just selected the current version on their system as the minimum version, without considering that this would cause extra work as everyone has to upgrade their CMake version.
> 
> We should not let a whimsical decision drive this much effort. If there is a real reason to go to CMake 3.19, we should hear it. Otherwise, we should push back and tell everyone to use a more reasonable version.

According to @DusanJovic-NOAA we need 3.18 or higher because it needs to support aliases of aliases. Maybe that for the way FMS is used in the ufs-weather-model and not a limitation imposed by FMS itself.

**Comment by kgerheiser** [comment]
Yes, it is required for aliases to be used in the weather model.

**Comment by DusanJovic-NOAA** [comment]
Cmake version 3.18+ is not required for the FMS itself, but, as the issue description says, for the ufs-weather-model.

https://cmake.org/cmake/help/latest/command/add_library.html#alias-libraries

_New in version 3.18: An ALIAS can target a non-GLOBAL Imported Target. Such alias is scoped to the directory in which it is created and below. The ALIAS_GLOBAL target property can be used to check if the alias is global or not._

An ALIAS that targets a non-GLOBAL Imported Target (i.e. another alias) is used here:
```
+if(FMS) 
+ find_package(FMS REQUIRED COMPONENTS R4 R8) 
+ if(32BIT) 
+   add_library(fms ALIAS FMS::fms_r4) 
+ else() 
+   add_library(fms ALIAS FMS::fms_r8) 
+ endif() 
+endif()
```
I do not think this is 'a whimsical decision'. I can not comment on whether this requires a lot of effort or not.
