### ISSUE TITLE
Update the nceppost with request by using the 10.0.0 version

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/hpc-stack#31]
Wen has added the nceppost with UPP version of 10.0.0. She request the installation test through hpc-stack.
We will first try it from the EMC_POST/develop branch, on each machine.
If it is okay, she needs to create a release to formally included in the hpc-stack.

A branch has been created to this issue
feature/postupdate

**Comment by kgerheiser** [comment]
What exactly is the problem?

**Comment by aerorahul** [comment]
EMC_Post is built as nceppost in hpc-stack.  The library it builds is called `libnceppost.a` and the module files export the variable `nceppost_ROOT` so that the UFS can find it via `find_package(nceppost)`.

EMC_Post is now producing the library as `libupp.a`.  `nceppost` was always going to be temporary stop gap measure until EMC_Post finalized what they want the library (and executable) to be called.  We also did not know what versioning they would adopt (if any).

It appears that they have now adopted the name `upp` in their library `libupp.a` and `upp.x` for the executable.
Also, they seem to have settled on a version number `10.0.0` for EMC_post (or UPP).

How does this affect `hpc-stack`?
One needs to:
1. add upp along side ncepppst in `build_nceplib.sh`
2. add a modulefile for upp similar to nceppost, but the variable we need in there is only `upp_ROOT`.  All other `POST_LIB` etc can be purged, because there is no need for them or an update is needed in the Makefiles to use `libupp.a`. They can key on `upp_ROOT`. This makes management of the modulefile simpler and cleaner.
3. update the yaml files to add a section on upp.

For an example see https://github.com/aerorahul/hpc-stack/tree/feature/upp

**Comment by Hang-Lei-NOAA** [comment]
Yes, Rahul is correct.
The similar changes has been used in the test version, feature/hpc-stack-nco
We wait for further testing results, and then merge back to develop

**Comment by edwardhartnett** [comment]
Have these changes been merged to develop?

**Comment by Hang-Lei-NOAA** [comment]
Yes, in both develop and feature/hpc-stack-nco branch. The test
installation based on  feature/hpc-stack-nco has been tested fine.

**Comment by edwardhartnett** [comment]
OK, I will close this issue.

**Comment by edwardhartnett** [comment]
I thought this had been completed, but apparently not?

**Comment by Hang-Lei-NOAA** [comment]
I will re-examine the develop branch, since the changes in the test
versions has no problem in UFS runs.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA see comments in #63

**Comment by Hang-Lei-NOAA** [comment]
So, it is the issue for Mac OS. We need someone who use MacOS to help

**Comment by aerorahul** [comment]
not just macOS. Also on ubuntu and mpich. See the other log
