### ISSUE TITLE
Can I add a config/config_linux_gnu.sh?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#327]
Can I add a config/config_linux_gnu.sh?

**Comment by kgerheiser** [comment]
What do you propose to have in it? I think a `config_linux_gnu` is a little too broad and there's not much configuration to do besides setting the compiler. 

Perhaps a specific OS like Ubuntu 20 with the default compilers. 

Otherwise,  you can set the HPC_* env variables and use `stack_custom.sh`.

**Comment by kgerheiser** [comment]
Closing this unless there's more to add.
