### ISSUE TITLE
Bug or not? Installing hpc-stack for two compilers in same directory structure leads to errors

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#33]
Not sure if this is a bug or intended.

I installed hpc-stack for the GNU compiler on cheyenne in
```
/glade/p/ral/jntp/GMTB/tools/hpc-stack-20201022
```
This creates the following directories underneath:
```
core
gnu-9.1.0
modulefiles
src # this one is mine
```
In a second step, I tried to install hpc-stack for the Intel compiler in the same directory structure, which then adds
```
intel-19.1.1
```
as expected. `./build_stack.sh` however fails with the error
```
+ echo 'WARNING: /glade/p/ral/jntp/GMTB/tools/hpc-stack-20201022/core/eigen/3.3.7 EXISTS, SKIPPING'
WARNING: /glade/p/ral/jntp/GMTB/tools/hpc-stack-20201022/core/eigen/3.3.7 EXISTS, SKIPPING
+ exit 1
BUILD FAIL!  Lib: eigen Error:1
```
Obviously the intel stack is trying to install the (compiler-independent because using native gnu?) eigen library again.

Is this intended? I would have thought that hpc-stack should either overwrite automatically or ignore building shared libraries in the `core` directory that are independent of the compiler and mpi library.

**Comment by aerorahul** [comment]
As you noticed, eigen library is compiler independent. So there is no point in installing eigen for GNU and then for Intel.
There is a global switch in `config.sh` named `OVERWRITE=Y|N` which prevents overwriting existing packages.
When a user wishes to install with a different compiler set, they should disable the `core` packages in the `stack.yaml` that they may have installed under the same installation prefix to prevent rebuilding (unless that is intentional)

So it is not a bug, but it is not a feature either.
We can put lots of if-then-else and complicated logic, but user intervention is necessary.

So we provide 3 choices for the user:
1. turn `OVERWRITE=Y` and if a package exists it will be overwritten.
2. turn packages `build: NO` in the `stack.yaml` to prevent re-building
3. use a different `stack.yaml` file with the core packages removed or follow 2. in 3.

**Comment by climbfuji** [comment]
> As you noticed, eigen library is compiler independent. So there is no point in installing eigen for GNU and then for Intel.
> There is a global switch in `config.sh` named `OVERWRITE=Y|N` which prevents overwriting existing packages.
> When a user wishes to install with a different compiler set, they should disable the `core` packages in the `stack.yaml` that they may have installed under the same installation prefix to prevent rebuilding (unless that is intentional)
> 
> So it is not a bug, but it is not a feature either.
> We can put lots of if-then-else and complicated logic, but user intervention is necessary.
> 
> So we provide 3 choices for the user:
> 
> 1. turn `OVERWRITE=Y` and if a package exists it will be overwritten.
> 2. turn packages `build: NO` in the `stack.yaml` to prevent re-building
> 3. use a different `stack.yaml` file with the core packages removed or follow 2. in 3.

Thanks, Rahul. The easiest way is 1. - a one-character change - if a user is doing what I am doing, i.e. installing the same version of the stack for two different compilers at the same time (i.e. with an identical OS / identical system libraries / default gnu compiler). I am doing that now, closing the issue.
