### ISSUE TITLE
gnu/9.2.0 hpc/1.1.0 sigio/2.3.2 library missing on Hera

### ISSUE THREAD

**Issue by MichaelLueken** [NOAA-EMC/hpc-stack#483]
**Describe the bug**
While attempting to build the GSI on Hera using gnu/9.2.0, the build failed with the following message:

```
CMake Error at src/gsi/CMakeLists.txt:66 (find_package):
  By not providing "Findsigio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "sigio", but
  CMake did not find one.

  Could not find a package configuration file provided by "sigio" with any of
  the following names:

    sigioConfig.cmake
    sigio-config.cmake
```
Following a `module show sigio/2.3.2`, I looked in:

`/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/`

and there is no `lib`, `include`, or `cmake` directory present.  In fact, this directory is completely empty.

**To Reproduce**

1) Clone the GSI repo - git clone --recursive git@github.com:NOAA-EMC/GSI.git
2) cd ush
3) Change `COMPILER=${COMPILER:-"intel"}` to `COMPILER=${COMPILER:-"gnu"}` in build.sh
4) Compile using `./build.sh`

**Expected behavior**
The GSI should be able to find the `cmake`, `include`, and `lib` directories in `/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/` and the code should compile without issue (the GSI was building using `hpc/1.1.0` `hpc-gnu/9.2.0` last Monday, August 15).

**System:**
This issue has been identified on Hera.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Michael, Please try do not use hpc-stack  build cmake/2.20.0. I just close it for you to test.  You can directly use the system installed cmake/2.20.1

**Comment by MichaelLueken** [comment]
Hi, @Hang-Lei-NOAA, I was building the GSI using `gnu/9.2.0` with the system installed `cmake/3.20.1` and not hpc-stack build `cmake/3.20.0`:

`   cmake/3.20.1       (L,D)`

The GSI still fails to compile because the GSI requires sigio (the following is from the GSI CMakeLists.txt file:

`find_package(sigio REQUIRED)`

and there is nothing present in the `sigio/2.3.2` directory for the `hpc/1.1.0` build with `gnu/9.2.0`:

```
[Michael.Lueken@hfe10 gsi]$ cd /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2
[Michael.Lueken@hfe10 2.3.2]$ ls
[Michael.Lueken@hfe10 2.3.2]$ 
```

**Comment by Hang-Lei-NOAA** [comment]
Please try it again. Thanks.
I used to have sigio problem due to lmod and cmake.

-bash-4.2$ ls
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/include
sigio_module.mod  sigio_r_module.mod
-bash-4.2$ module load sigio
-bash-4.2$ module show sigio
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/compiler/gnu/9.2.0/sigio/2.3.2.lua:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[]])
conflict("sigio")
setenv("sigio_ROOT","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2")
setenv("sigio_VERSION","2.3.2")
setenv("SIGIO_INC","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/include")
setenv("SIGIO_LIB","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/lib/libsigio.a")
setenv("SIGIO_INC4","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/include")
setenv("SIGIO_LIB4","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/lib/libsigio.a")
whatis("Name: sigio")
whatis("Version: 2.3.2")
whatis("Category: library")
whatis("Description: sigio library")

-bash-4.2$ ls -l
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/lib/libsigio.a
-rw-r--r-- 1 Hang.Lei nwprod 560054 Aug 22 17:20
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/gnu-9.2.0/sigio/2.3.2/lib/libsigio.a

**Comment by MichaelLueken** [comment]
Hi, @Hang-Lei-NOAA.  Thank you very much!  I was successfully able to compile the GSI with the `hpc/1.1.0` `gnu/9.2.0` settings.
