### ISSUE TITLE
Remove all branches except develop and master/main.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#60]
As per NOAA-EMC policy (I cannot find a link to that policy), only the main branches will be available on this repository.
Users are encouraged to fork the repository to create local branches and issue a PR when ready.

This repository will become read-only to the public and all PR's will need approvals.

The following branches will be removed on **Nov 30, 2020** ; owners please take note and sync.

| Branch Name | Owner | Status |
| -------- | ---- | --- |
| feature/wcoss2| @aerorahul| Removed |
| feature/gaea|  @aerorahul|  Removed |
| feature/hera-gnu | @aerorahul|  Removed |
| feature/hpc-stack-nco | @Hang-Lei-NOAA | 
| feature/wcoss2-mods | @mark-a-potts|  Removed

**Comment by edwardhartnett** [comment]
I would like to hear more of this policy actually.

I believe the repo is already read-only to the public and PRs already need approval. Do you mean something additional?

**Comment by aerorahul** [comment]
I was told, that no one (including admins) should create branches on the noaa-emc repos.  Developers should fork and push branches to their forks and issue PR's.

**Comment by edwardhartnett** [comment]
I think that's a little too strict. Let's get the 1.1.0 release out, remove the existing feature nco branch, and then discuss with @kgerheiser , @Hang-Lei-NOAA and any other interested parties.

**Comment by edwardhartnett** [comment]
OK, looks like the hpc-stack-nco branch has been removed. We'll keep this issue open until we decide whether or not developers are allowed to create development branches in the repo, or whether they must fork and create branches only in their fork.

I suggest that we should let developers create branches for the following reasons:
* Less operations, less chance for mistakes, by not maintaining a fork.
* Greater visibility by team-mates, better support for suddenly-departing staff.
* Greater ease with local CI systems, like my local jenkins CI.

I would suggest that developers should be creating approximately one short-lived branch at a time. No one should be allowed to proliferate branches, or keep them around for more than a few weeks at most. 

However, if the consensus is otherwise, I can use a fork. That's what I do at George's request on UFS_UTILS.

I'm happy to conform to any local branch naming conventions, but I like to start my branches with `ejh_`, because that allows my Jenkins server to test all my branches automatically. (I don't believe we need any branch naming conventions, the names don't really matter much.)

In all cases, programmers and users must be discouraged from maintaining long-lived branches with many changes. Submitting such a branch as a PR creates a lot of extra work for other programmers. Review happens best in small increments, and review is a required part of our process.

Programmers must modify work habits to support the process. This can be uncomfortable at first, but the long-term reward is higher quality software, with less defects, and lower support costs.

**Comment by Hang-Lei-NOAA** [comment]
Agree with Edward.

**Comment by edwardhartnett** [comment]
OK, unless @kgerheiser disagrees, we will close this issue with the understanding that developers on hpc-stack can create one (or few) short-lived branches which are only there to merge to develop. No external users will develop code based on these branches. Only official release branches are supported.
