### ISSUE TITLE
Reduce the number of stack files

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#94]
The more stack files that are added the more tedious it becomes to maintain nearly identical files and the more chance for errors. 

What ones do we really need and what ones we can get rid of or combine, if any:

`stack_mac.yaml`: Builds MPI by default, disables OpenMP on certain libraries because Clang doesn't have it, builds shared libraries

`stack_custom.yaml`: This is the default config is no other is specified, builds shared libraries

`stack_gaea.yaml`: For Gaea, disables building a bunch of libraries, build static libs

`stack_ncar.yaml`: The only difference from `stack_noaa.yaml` is that it doesn't build json and json_schema_validator

`stack_noaa.yaml`: Doesn't contain options for gnu and MPI, compared to `stack_custom.yaml`, builds static libraries

`stack_ufs_weather_ci.yaml`: Disables building a bunch of libraries, builds shared libraries

**Comment by Hang-Lei-NOAA** [comment]
We can follow Rahul's suggestion to add a stack_add.ymal to add additional versions. e.g esmf bs36 etc.

**Comment by climbfuji** [comment]
I can try to compile the NOAA stack on gaea, but I am pretty sure this will be an uphill battle. Regarding macOS: when using LLVM clang that comes via homebrew (just as GNU does), there is OpenMP support. The nice thing about using LLVM clang + GNU gfortran is then that the same config can be used with GNU gcc + GNU gfortran and have OpenMP support. I have instructions on how to do that, compiled hpc-stack on macOS Catalina with LLVM clang 10 and GNU gfortran 10 as well as with GNU gcc+gfortran 10 (I also tried with 9 on macOS Mojave0.

**Comment by aerorahul** [comment]
IMHO

noaa, gaea, ncar should be combined into one.  These will build static and all libraries (except compiler and mpi).
The libraries are used by a variety of applications; ufs, jedi, etc.

custom and mac are used for CI and should build all libraries.  Static/Shared does it matter for CI?

ufs_weather_ci could be eliminated in favor of (noaa, gaea, ncar).  Sure, there is overhead (extra space/time) due to additional libraries in the container, but what is the size difference in the container including/excluding these additional libraries? This should be evaluated.

**Comment by edwardhartnett** [comment]
Let's bump this issue to the 1.3.0 release of hpc-stack so we can get the 1.2.0 release out.

**Comment by kgerheiser** [comment]
Going to close this. I think we're fine with the files we support. Mac, custom, and NOAA are general purpose while we have other more specialized stacks.
